.\"
.\" Copyright (c) FreeGLUT contributors, 2000-2025.
.\"
.\" See the file "man/LICENSE" for information on usage and redistribution
.\"
.TH glutForceJoystickFunc 3GLUT "3.8" "FreeGLUT" "FreeGLUT"
.SH NAME
glutForceJoystickFunc - forces a joystick callback call.
.SH SYNTAX
.nf
.LP
void glutForceJoystickFunc(void);
.fi
.SH DESCRIPTION
glutForceJoystickFunc forces a single call to the joystick callback immediately, bypassing the normal timer-based polling mechanism. This is useful when an application needs to check the joystick state on demand, rather than waiting for the next scheduled callback.

The joystick callback must have been previously registered with glutJoystickFunc for this function to have any effect.

This function is particularly useful in situations where the application needs to get the most current joystick data at specific points in time, such as at the beginning of a game level or when a user explicitly requests recalibration.

This function is a FreeGLUT extension and is not available in the original GLUT library.

.SH EXAMPLE
.nf
/* Joystick callback function */
void joystickCallback(unsigned int buttonMask, int x, int y, int z)
{
    /* Process joystick input */
    printf("Joystick: buttons=%u, position=(%d, %d, %d)\\n", 
           buttonMask, x, y, z);
}

/* Initialize joystick with 100ms polling interval */
glutJoystickFunc(joystickCallback, 100);

/* Later, when immediate joystick input is needed */
void checkJoystickNow(void)
{
    /* Force immediate call to joystick callback */
    glutForceJoystickFunc();
    /* joystickCallback will be called with current joystick data */
}
.fi

.SH SEE ALSO
glutJoystickFunc, glutJoystickSetDeadBand, glutJoystickSetSaturation
.SH AUTHOR
FreeGLUT contributors
