/*
 * Mouse wheel and mouse callback counter.
 *
 * This program is useful for comparing the number of callbacks generated by
 * the different freeglut window-system backends for the same wheel gesture,
 * and for verifying fallback to mouse button callbacks when mouse wheel
 * callback is uninstalled.
 */
#include <stdio.h>
#include <stdlib.h>
#include <GL/freeglut.h>

#define MAX_WHEELS  4
#define MAX_BUTTONS 12

typedef struct WheelCount {
    unsigned long callbacks;
    unsigned long positive;
    unsigned long negative;
    long          net;
} WheelCount;

typedef struct ButtonCount {
    unsigned long callbacks;
    unsigned long down;
    unsigned long up;
} ButtonCount;

static WheelCount  wheels[MAX_WHEELS];
static ButtonCount buttons[MAX_BUTTONS];

static unsigned long total_wheel_callbacks;
static unsigned long other_wheels;
static int           last_wheel;
static int           last_wheel_direction;
static int           last_wheel_x;
static int           last_wheel_y;
static int           have_last_wheel;

static unsigned long total_mouse_callbacks;
static unsigned long other_buttons;
static int           last_mouse_button;
static int           last_mouse_state;
static int           last_mouse_x;
static int           last_mouse_y;
static int           have_last_mouse;

static int  wheel_callback_installed = 1;
static void mouseWheel( int wheel, int direction, int x, int y );

static int window_width  = 640;
static int window_height = 500;

static const char *getButtonName( int button )
{
    switch ( button ) {
    case GLUT_LEFT_BUTTON:
        return "Left";
    case GLUT_MIDDLE_BUTTON:
        return "Middle";
    case GLUT_RIGHT_BUTTON:
        return "Right";
    case 3:
        return "Wheel 0 Up";
    case 4:
        return "Wheel 0 Down";
    case 5:
        return "Wheel 1 Up";
    case 6:
        return "Wheel 1 Down";
    case 7:
        return "Wheel 2 Up";
    case 8:
        return "Wheel 2 Down";
    case 9:
        return "Wheel 3 Up";
    case 10:
        return "Wheel 3 Down";
    default:
        return "Other";
    }
}

static const char *getStateName( int state )
{
    switch ( state ) {
    case GLUT_DOWN:
        return "GLUT_DOWN";
    case GLUT_UP:
        return "GLUT_UP";
    default:
        return "UNKNOWN";
    }
}

static void drawString( int x, int y, const char *string )
{
    glRasterPos2i( x, y );
    glutBitmapString( GLUT_BITMAP_9_BY_15, (const unsigned char *)string );
}

static void display( void )
{
    char line[160];
    int  wheel;
    int  button;
    int  y = 30;

    glClear( GL_COLOR_BUFFER_BIT );
    glColor3f( 0.9f, 0.9f, 0.9f );

    drawString( 20, y, "Mouse wheel & mouse callback counter" );
    y += 24;

    sprintf( line,
        "Mouse wheel callback: %s (press 'W' to toggle)",
        wheel_callback_installed ? "INSTALLED" : "UNINSTALLED" );
    drawString( 20, y, line );
    y += 28;

    sprintf( line, "--- Mouse Wheel Callbacks (Total: %lu) ---", total_wheel_callbacks );
    drawString( 20, y, line );
    y += 22;

    for ( wheel = 0; wheel < MAX_WHEELS; ++wheel ) {
        sprintf( line,
            "Wheel %d: %lu callbacks  +1: %lu  -1: %lu  net: %ld",
            wheel,
            wheels[wheel].callbacks,
            wheels[wheel].positive,
            wheels[wheel].negative,
            wheels[wheel].net );
        drawString( 20, y, line );
        y += 20;
    }

    if ( other_wheels ) {
        sprintf( line, "Callbacks for wheel numbers >= %d: %lu", MAX_WHEELS, other_wheels );
        drawString( 20, y, line );
        y += 20;
    }

    if ( have_last_wheel )
        sprintf( line,
            "Last wheel callback: wheel %d, direction %+d, x %d, y %d",
            last_wheel,
            last_wheel_direction,
            last_wheel_x,
            last_wheel_y );
    else
        sprintf( line, "Last wheel callback: none" );
    drawString( 20, y, line );
    y += 28;

    sprintf( line, "--- Mouse Button Callbacks (Total: %lu) ---", total_mouse_callbacks );
    drawString( 20, y, line );
    y += 22;

    for ( button = 0; button < 5; ++button ) {
        sprintf( line,
            "Button %d (%-12s): %lu callbacks  down: %lu  up: %lu",
            button,
            getButtonName( button ),
            buttons[button].callbacks,
            buttons[button].down,
            buttons[button].up );
        drawString( 20, y, line );
        y += 20;
    }

    for ( button = 5; button < MAX_BUTTONS; ++button ) {
        if ( buttons[button].callbacks > 0 ) {
            sprintf( line,
                "Button %d (%-12s): %lu callbacks  down: %lu  up: %lu",
                button,
                getButtonName( button ),
                buttons[button].callbacks,
                buttons[button].down,
                buttons[button].up );
            drawString( 20, y, line );
            y += 20;
        }
    }

    if ( other_buttons ) {
        sprintf( line, "Callbacks for button numbers >= %d: %lu", MAX_BUTTONS, other_buttons );
        drawString( 20, y, line );
        y += 20;
    }

    if ( have_last_mouse )
        sprintf( line,
            "Last mouse callback: button %d (%s), %s, x %d, y %d",
            last_mouse_button,
            getButtonName( last_mouse_button ),
            getStateName( last_mouse_state ),
            last_mouse_x,
            last_mouse_y );
    else
        sprintf( line, "Last mouse callback: none" );
    drawString( 20, y, line );

    drawString( 20, window_height - 20, "Scroll or click.  W toggles wheel CB; R resets; Esc or Q quits." );
    glutSwapBuffers( );
}

static void reshape( int width, int height )
{
    window_width  = width;
    window_height = height;

    glViewport( 0, 0, width, height );
    glMatrixMode( GL_PROJECTION );
    glLoadIdentity( );
    glOrtho( 0, width, height, 0, -1, 1 );
    glMatrixMode( GL_MODELVIEW );
    glLoadIdentity( );
}

static void mouseWheel( int wheel, int direction, int x, int y )
{
    ++total_wheel_callbacks;

    if ( wheel >= 0 && wheel < MAX_WHEELS ) {
        WheelCount *count = &wheels[wheel];

        ++count->callbacks;
        count->net += direction;
        if ( direction > 0 )
            ++count->positive;
        else if ( direction < 0 )
            ++count->negative;
    }
    else
        ++other_wheels;

    last_wheel           = wheel;
    last_wheel_direction = direction;
    last_wheel_x         = x;
    last_wheel_y         = y;
    have_last_wheel      = 1;
    glutPostRedisplay( );
}

static void mouse( int button, int state, int x, int y )
{
    ++total_mouse_callbacks;

    if ( button >= 0 && button < MAX_BUTTONS ) {
        ButtonCount *count = &buttons[button];

        ++count->callbacks;
        if ( state == GLUT_DOWN )
            ++count->down;
        else if ( state == GLUT_UP )
            ++count->up;
    }
    else
        ++other_buttons;

    last_mouse_button = button;
    last_mouse_state  = state;
    last_mouse_x      = x;
    last_mouse_y      = y;
    have_last_mouse   = 1;
    glutPostRedisplay( );
}

static void toggleWheelCallback( void )
{
    wheel_callback_installed = !wheel_callback_installed;
    if ( wheel_callback_installed )
        glutMouseWheelFunc( mouseWheel );
    else
        glutMouseWheelFunc( NULL );
    glutPostRedisplay( );
}

static void resetCounts( void )
{
    int wheel;
    int button;

    for ( wheel = 0; wheel < MAX_WHEELS; ++wheel ) {
        wheels[wheel].callbacks = 0;
        wheels[wheel].positive  = 0;
        wheels[wheel].negative  = 0;
        wheels[wheel].net       = 0;
    }
    total_wheel_callbacks = 0;
    other_wheels          = 0;
    have_last_wheel       = 0;

    for ( button = 0; button < MAX_BUTTONS; ++button ) {
        buttons[button].callbacks = 0;
        buttons[button].down      = 0;
        buttons[button].up        = 0;
    }
    total_mouse_callbacks = 0;
    other_buttons         = 0;
    have_last_mouse       = 0;

    glutPostRedisplay( );
}

static void keyboard( unsigned char key, int x, int y )
{
    (void)x;
    (void)y;

    switch ( key ) {
    case 'w':
    case 'W':
        toggleWheelCallback( );
        break;
    case 'r':
    case 'R':
        resetCounts( );
        break;
    case 'q':
    case 'Q':
    case 27:
        glutLeaveMainLoop( );
        break;
    }
}

int main( int argc, char **argv )
{
    glutInit( &argc, argv );
    glutInitDisplayMode( GLUT_RGB | GLUT_DOUBLE );
    glutInitWindowSize( window_width, window_height );
    glutCreateWindow( "freeglut mouse wheel & mouse counter" );

    glClearColor( 0.08f, 0.09f, 0.12f, 1.0f );
    glutDisplayFunc( display );
    glutReshapeFunc( reshape );
    glutKeyboardFunc( keyboard );
    glutMouseWheelFunc( mouseWheel );
    glutMouseFunc( mouse );
    glutMainLoop( );
    return EXIT_SUCCESS;
}
